# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Haskell Linter
on: [pull_request]

jobs:
  hlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: domdere/haskell-lint-action@v1.0.2
    env:	
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
